language: node_js
node_js:
  - node
before_script:
  - npm run lint
  - npm run build
script:
  - npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: cj@specialblend.net
  api_key: $NPM_TOKEN
  on:
    branch: master
